# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdc273f1f644091a0f6045672476efabf38788bd7243db83350f7044fa1d74156c15316ec3c15d1e823318aea40e1b42d7d60b93e2d3c850ab49d5adebdbaf3c

test:
  secret_key_base: 956d868b09db65557354c15e4d96138ffef3edec1da1f98b67dc20e19ea62bdcdca4836bd03f7ced4971431eac37250589e0b29305c63c70698cd35a9cd249d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
